### ISSUE TITLE
'Open new tab' In MacOS Sierra Terminal opens in the home folder always

### ISSUE THREAD

**Issue by protoiyer** [riobard/bash-powerline#14]
#.. when it is supposed to open the new _tab_ in the same folder from where Cmd+T (Shell | New Tab | New Tab with [same] Settings) was pressed. Oh, and I am using the default bash terminal.

This works fine in Ubuntu 16.04 (when I press Ctrl+Shift+T to open a new tab).

The only change I have made to the bash-powerline.sh file (in Mac and Ubuntu) is to add one line to the function ps1() to add a new line  #character:
        PS1+="\e[m \n\$ "  

And, in .bashrc, the last line is this
source ~/.bash-powerline.sh

It works fine in MacOS if I uncomment the above last line in .bashrc.

Any idea how to resolve this? Thanks.

**Comment by riobard** [comment]
I don't know why it behaves that way, but I'd suggest you try iTerm2 instead. Much better than Terminal.

**Comment by protoiyer** [comment]
Ok. Thanks for looking into this. I revisited some SO.com posts that I was checking in the morning, and from one of them got the missing piece that resolves the issue (towards the end - line# 156):

    # PROMPT_COMMAND=ps1                                          # <- existing code, commented out
    PROMPT_COMMAND="ps1; $PROMPT_COMMAND"  # <- needed for Mac OS Sierra

**Comment by narkowicz** [comment]
Following up after encountering on a fresh install - this is something that will continue to affect the default behaviour in Terminal.app on macOS / X which sets `PROMPT_COMMAND` to `update_terminal_cwd` when set to open new tabs or windows in the same working directory.

@riobard would you consider updating (or accepting a PR) so that `PROMPT_COMMAND` is appended as described by @protoiyer in order to solve this problem on macOS? i.e.

`PROMPT_COMMAND="$PROMPT_COMMAND;  ps1"`

This shouldn't hurt other platforms and would play nice with any other prompt commands - unless there is a reason for overriding on some configurations?

Alternatively, suggest adding a description to the README as a reminder to others and future self.

**Comment by riobard** [comment]
@narkowicz I don’t personally use Terminal.app, but a PR to fix the issue would be highly appreciated :)
